# LingoWhale 语鲸会员解锁配置
# 资源标签: 语鲸解锁

[rewrite_local]
^https://api-public\.lingowhale\.com/api/lingowhale/v1/.* url script-request-header https://raw.githubusercontent.com/joeshu/For-ADM/refs/heads/master/yujing.js
^https://api-public\.lingowhale\.com/api/lingowhale/v1/.* url script-response-body https://raw.githubusercontent.com/joeshu/For-ADM/refs/heads/master/yujing.js

[mitm]
hostname = api-public.lingowhale.com

